apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
# completions: 5 / 실행해야할 job의 수가 몇개인지 지정, replicas 와 비슷한 옵션으로 3개를 실행하고 종료, 동시에 running 되지는 않는다.
# parallelism: 2 / 병렬성, 동시 running 되는 pod 수 : 2개 동시 실행되는 옵션
# activeDeadlineSeconds: 5 / 지정시간내에 job 을 완료
  template:
    spec:
    containers:
    - name: centos-container
      image: centos:7
      command:["bash"]
      args:
      - "c"
      - "echo 'hello world'; sleep 50; echo 'bye'"
   restartPolicy: Never # 컨테이너 실행 > 오류가 있는 컨테이너를 재시작하지 안고, 다른 pod 를 재시작한다.
 # restartPolicy: OnFailure / 컨테이너를 3번 재시작하고 그래도 정상종료가 안되면 프로세서 종료 > pod 삭제
 # backoffLimit: 3
