apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
# completions: 5 / 실행해야할 job의 수가 몇개인지 지정
# parallelism: 2 / 병렬성, 동시 running 되는 pod 수
# activeDeadlineSeconds: 5 / 지정시간내에 job 을 완료
  template:
    spec:
    containers:
    - name: centos-container
      image: centos:7
      command:["bash"]
      args:
      - "c"
      - "echo 'hello world'; sleep 50; echo 'bye'"
   restartPolicy: Never # pod 를 3번 재시작하다가 그래도 정상종료가 안되면 프로세서 종료
 # restartPolicy: OnFailure / 컨테이너를 3번 재시작하고 그래도 정상종료가 안되면 프로세서 종료
 # backoffLimit: 3
